trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
    - master

pool:
  vmImage: macOS-10.14
  demands: xcode

variables:
  workspace: 'Bluepill.xcworkspace'
  xcodeVersion: 'specifyPath'
  xcodeDeveloperDir: '/Applications/Xcode_10.2.app/Contents/Developer'

steps:

- script: ./scripts/bluepill.sh build
  displayName: 'Build BluePill'

- script: ./scripts/bluepill.sh test
  displayName: 'Run BluePill tests'

- task: CopyFiles@2
  inputs:
    contents: |
      build/**/bp
      build/**/bluepill
    targetFolder: '$(Build.artifactStagingDirectory)'

- script: 'ls -alR'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
