# TODO: integrate logic from scripts/bluepill.sh

trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
    - master

pool:
  vmImage: macOS-10.14
  demands: xcode

variables:
  workspace: 'Bluepill.xcworkspace'
  scheme: 'bluepill'
  xcodeVersion: 'specifyPath'
  xcodeDeveloperDir: '/Applications/Xcode_10.2.app/Contents/Developer'

steps:
- task: Xcode@5
  displayName: 'Xcode build'
  inputs:
    configuration: 'Release'
    sdk: 'macosx'
    xcWorkspacePath: $(workspace)
    scheme: $(scheme)
    xcodeVersion: $(xcodeVersion)
    xcodeDeveloperDir: $(xcodeDeveloperDir)

- task: Xcode@5
  displayName: 'Xcode test'
  inputs:
    actions: test
    configuration: 'Debug'
    sdk: 'macosx'
    xcWorkspacePath: $(workspace)
    scheme: $(scheme)
    xcodeVersion: $(xcodeVersion)
    xcodeDeveloperDir: $(xcodeDeveloperDir)
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone X'
    publishJUnitResults: true